# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
range_vector = np.arange(10,49)
range_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [4]:
range_vector.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
range_vector.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
v = np.__version__


print(v)
print("---------------------------------------------------------------------")
np.show_config()


1.18.5
---------------------------------------------------------------------
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ResidentEvil/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/ResidentEvil/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ResidentEvil/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include'

7. Print the dimension of the array in question 3


In [7]:
range_vector.ndim

1

8. Create a boolean array with all the True values

In [8]:
boolean_array = np.array([True, True, True])
boolean_array

array([ True,  True,  True])

9. Create a two dimensional array




In [9]:
two_d_array = np.ones((2,3))


10. Create a three dimensional array



In [10]:
three_d_array = np.ones((2,3,3))
three_d_array

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
any_vector = np.array([1,2,3,4])
reverse_vector = any_vector[::-1]
reverse_vector

array([4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
n_vector = np.zeros(10)
n_vector[4]=1
n_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
identity_natrix = np.ones((3,3))
identity_natrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1,2,3,4,5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr11 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr22 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr11 == arr22

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
odd_num = np.arange(10)
odd_num[1::2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
np.where(odd_num % 2 != 0 , -1 , odd_num)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
big_box = np.ones((5,5))
big_box[1:-1,1:-1]=0
big_box

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d [0][0] = 64 # for first 1d array
a = arr3d
print(a)

arr3d [0] = 64 # for first 2d array
b = arr3d
print(b)


[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
two_d_arr = np.arange((9))
new_two = two_d_arr.reshape(3,3)
new_two[0]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
two_d_arr = np.arange((9))
new_two = two_d_arr.reshape(3,3)
new_two[1][1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
two_d_arr = np.arange((9))
new_two = two_d_arr.reshape(3,3)
new_two[0:2,2]

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
random_mat = np.random.randn(100)
rand_rearr = random_mat.reshape(10,10)
min_n = np.min(rand_rearr)
max_n = np.max(rand_rearr)
print(min_n)
print(max_n)

-2.3011757573746645
2.7257035153384486


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = a==b
d = np.where(c==True)
d

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [41]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[~(names == '!Will')]


array([[ 0.63196748, -0.44400691, -1.41932451,  0.38725899],
       [-0.17958849,  0.87874701,  0.09273529, -0.41317055],
       [ 1.1123357 ,  0.15871332, -0.00269282, -1.64367628],
       [ 0.49212213,  1.93130448, -1.42819691, -1.90410874],
       [ 1.1203873 ,  0.35999126, -0.31796146, -0.63628457],
       [-1.09191194,  0.18018289,  0.77153393, -1.96774345],
       [ 1.17163941, -0.86812018, -0.65925018,  0.32801274]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask = (names == 'Joe') | (names == 'Will')
data[mask]


array([[-1.81382606, -0.237825  , -0.47231598, -0.917259  ],
       [-0.49650958,  0.70645648, -0.22391686,  0.5793727 ],
       [-1.29435968, -1.20027784, -0.94173256, -0.20117963],
       [ 2.41865407,  0.70434193, -1.89839518,  2.0624229 ],
       [ 0.51883253, -0.19585597, -0.36472829, -0.11066668]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [29]:
x = np.arange(1,16)
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [30]:
x = np.arange(1,17)
x.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [31]:
x = np.arange(1,17)
y = x.reshape(2,2,4)
z = y[::-1]
z

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [32]:
x = np.sqrt(np.arange(10))
np.where(x<0.5,0,x)
x



array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [33]:
a = np.empty(10) 
b = np.empty(10)
print(a)
print(b)
c = np.array([a.max(),b.max()])
c

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[5.11798224e-307 3.44897992e-307 1.69118108e-306 9.34609790e-307
 6.23037657e-307 1.11260348e-306 1.37962049e-306 2.22521238e-306
 1.24611470e-306 0.00000000e+000]


array([3.00000000e+000, 2.22521238e-306])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [34]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x = np.unique(names)
x

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [35]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

c = np.intersect1d(a,b)

a[a!=c]

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [36]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,[1]] = newColumn[:,[0]]
sampleArray


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [37]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [44]:
x = np.cumsum(np.random.randn(20))
x

array([ 1.3028343 ,  1.26617813,  1.57479918,  2.28227873,  2.35811332,
        4.24948995,  4.42141261,  5.9820169 ,  7.06565651,  6.64749736,
        8.62258588,  7.30209294,  8.24817476,  9.06868241, 10.54535972,
       10.2870417 , 10.47237336,  8.98083188,  9.70754107, 10.62659923])

### Auria Ahmad | PIAIC90066 | Assignment # 1 Assignment#1(NumPy Fundamentals) (15-Dec-2020)